when@dev:
    web_profiler:
        toolbar: false

    framework:
        profiler:
            collect: false
            collect_serializer_data: false

when@test:
    framework:
        profiler: { collect: false }
